// Generated by gencpp from file pepper_ws/harvest.msg
// DO NOT EDIT!


#ifndef PEPPER_WS_MESSAGE_HARVEST_H
#define PEPPER_WS_MESSAGE_HARVEST_H

#include <ros/service_traits.h>


#include <pepper_ws/harvestRequest.h>
#include <pepper_ws/harvestResponse.h>


namespace pepper_ws
{

struct harvest
{

typedef harvestRequest Request;
typedef harvestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct harvest
} // namespace pepper_ws


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pepper_ws::harvest > {
  static const char* value()
  {
    return "49ea530aae91150cd4645ab17a741cf0";
  }

  static const char* value(const ::pepper_ws::harvest&) { return value(); }
};

template<>
struct DataType< ::pepper_ws::harvest > {
  static const char* value()
  {
    return "pepper_ws/harvest";
  }

  static const char* value(const ::pepper_ws::harvest&) { return value(); }
};


// service_traits::MD5Sum< ::pepper_ws::harvestRequest> should match
// service_traits::MD5Sum< ::pepper_ws::harvest >
template<>
struct MD5Sum< ::pepper_ws::harvestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_ws::harvest >::value();
  }
  static const char* value(const ::pepper_ws::harvestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_ws::harvestRequest> should match
// service_traits::DataType< ::pepper_ws::harvest >
template<>
struct DataType< ::pepper_ws::harvestRequest>
{
  static const char* value()
  {
    return DataType< ::pepper_ws::harvest >::value();
  }
  static const char* value(const ::pepper_ws::harvestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pepper_ws::harvestResponse> should match
// service_traits::MD5Sum< ::pepper_ws::harvest >
template<>
struct MD5Sum< ::pepper_ws::harvestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_ws::harvest >::value();
  }
  static const char* value(const ::pepper_ws::harvestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_ws::harvestResponse> should match
// service_traits::DataType< ::pepper_ws::harvest >
template<>
struct DataType< ::pepper_ws::harvestResponse>
{
  static const char* value()
  {
    return DataType< ::pepper_ws::harvest >::value();
  }
  static const char* value(const ::pepper_ws::harvestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEPPER_WS_MESSAGE_HARVEST_H
