// Generated by gencpp from file pepper_ws/visual_servo.msg
// DO NOT EDIT!


#ifndef PEPPER_WS_MESSAGE_VISUAL_SERVO_H
#define PEPPER_WS_MESSAGE_VISUAL_SERVO_H

#include <ros/service_traits.h>


#include <pepper_ws/visual_servoRequest.h>
#include <pepper_ws/visual_servoResponse.h>


namespace pepper_ws
{

struct visual_servo
{

typedef visual_servoRequest Request;
typedef visual_servoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visual_servo
} // namespace pepper_ws


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pepper_ws::visual_servo > {
  static const char* value()
  {
    return "49ea530aae91150cd4645ab17a741cf0";
  }

  static const char* value(const ::pepper_ws::visual_servo&) { return value(); }
};

template<>
struct DataType< ::pepper_ws::visual_servo > {
  static const char* value()
  {
    return "pepper_ws/visual_servo";
  }

  static const char* value(const ::pepper_ws::visual_servo&) { return value(); }
};


// service_traits::MD5Sum< ::pepper_ws::visual_servoRequest> should match
// service_traits::MD5Sum< ::pepper_ws::visual_servo >
template<>
struct MD5Sum< ::pepper_ws::visual_servoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_ws::visual_servo >::value();
  }
  static const char* value(const ::pepper_ws::visual_servoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_ws::visual_servoRequest> should match
// service_traits::DataType< ::pepper_ws::visual_servo >
template<>
struct DataType< ::pepper_ws::visual_servoRequest>
{
  static const char* value()
  {
    return DataType< ::pepper_ws::visual_servo >::value();
  }
  static const char* value(const ::pepper_ws::visual_servoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pepper_ws::visual_servoResponse> should match
// service_traits::MD5Sum< ::pepper_ws::visual_servo >
template<>
struct MD5Sum< ::pepper_ws::visual_servoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_ws::visual_servo >::value();
  }
  static const char* value(const ::pepper_ws::visual_servoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_ws::visual_servoResponse> should match
// service_traits::DataType< ::pepper_ws::visual_servo >
template<>
struct DataType< ::pepper_ws::visual_servoResponse>
{
  static const char* value()
  {
    return DataType< ::pepper_ws::visual_servo >::value();
  }
  static const char* value(const ::pepper_ws::visual_servoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEPPER_WS_MESSAGE_VISUAL_SERVO_H
