// Generated by gencpp from file system_ws/harvestRequest.msg
// DO NOT EDIT!


#ifndef SYSTEM_WS_MESSAGE_HARVESTREQUEST_H
#define SYSTEM_WS_MESSAGE_HARVESTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace system_ws
{
template <class ContainerAllocator>
struct harvestRequest_
{
  typedef harvestRequest_<ContainerAllocator> Type;

  harvestRequest_()
    : req_id(0)  {
    }
  harvestRequest_(const ContainerAllocator& _alloc)
    : req_id(0)  {
  (void)_alloc;
    }



   typedef int16_t _req_id_type;
  _req_id_type req_id;





  typedef boost::shared_ptr< ::system_ws::harvestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::system_ws::harvestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct harvestRequest_

typedef ::system_ws::harvestRequest_<std::allocator<void> > harvestRequest;

typedef boost::shared_ptr< ::system_ws::harvestRequest > harvestRequestPtr;
typedef boost::shared_ptr< ::system_ws::harvestRequest const> harvestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::system_ws::harvestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::system_ws::harvestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::system_ws::harvestRequest_<ContainerAllocator1> & lhs, const ::system_ws::harvestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.req_id == rhs.req_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::system_ws::harvestRequest_<ContainerAllocator1> & lhs, const ::system_ws::harvestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace system_ws

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::system_ws::harvestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::system_ws::harvestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_ws::harvestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::system_ws::harvestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_ws::harvestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::system_ws::harvestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::system_ws::harvestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d67e2fcd47f3255cc3fbcfba8a121186";
  }

  static const char* value(const ::system_ws::harvestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd67e2fcd47f3255cULL;
  static const uint64_t static_value2 = 0xc3fbcfba8a121186ULL;
};

template<class ContainerAllocator>
struct DataType< ::system_ws::harvestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "system_ws/harvestRequest";
  }

  static const char* value(const ::system_ws::harvestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::system_ws::harvestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 req_id\n"
;
  }

  static const char* value(const ::system_ws::harvestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::system_ws::harvestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct harvestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::system_ws::harvestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::system_ws::harvestRequest_<ContainerAllocator>& v)
  {
    s << indent << "req_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.req_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SYSTEM_WS_MESSAGE_HARVESTREQUEST_H
