// Generated by gencpp from file manipulation/dpoi.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_DPOI_H
#define MANIPULATION_MESSAGE_DPOI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace manipulation
{
template <class ContainerAllocator>
struct dpoi_
{
  typedef dpoi_<ContainerAllocator> Type;

  dpoi_()
    : header()
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
    }
  dpoi_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _dx_type;
  _dx_type dx;

   typedef double _dy_type;
  _dy_type dy;

   typedef double _dz_type;
  _dz_type dz;





  typedef boost::shared_ptr< ::manipulation::dpoi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation::dpoi_<ContainerAllocator> const> ConstPtr;

}; // struct dpoi_

typedef ::manipulation::dpoi_<std::allocator<void> > dpoi;

typedef boost::shared_ptr< ::manipulation::dpoi > dpoiPtr;
typedef boost::shared_ptr< ::manipulation::dpoi const> dpoiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation::dpoi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation::dpoi_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulation::dpoi_<ContainerAllocator1> & lhs, const ::manipulation::dpoi_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.dz == rhs.dz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulation::dpoi_<ContainerAllocator1> & lhs, const ::manipulation::dpoi_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulation::dpoi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation::dpoi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::dpoi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::dpoi_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::dpoi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::dpoi_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation::dpoi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b83bf91e81f8ba47dfcdd1eb5ea305e";
  }

  static const char* value(const ::manipulation::dpoi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b83bf91e81f8ba4ULL;
  static const uint64_t static_value2 = 0x7dfcdd1eb5ea305eULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation::dpoi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation/dpoi";
  }

  static const char* value(const ::manipulation::dpoi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation::dpoi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 dx\n"
"float64 dy\n"
"float64 dz\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::manipulation::dpoi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation::dpoi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.dz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dpoi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation::dpoi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation::dpoi_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dx: ";
    Printer<double>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<double>::stream(s, indent + "  ", v.dy);
    s << indent << "dz: ";
    Printer<double>::stream(s, indent + "  ", v.dz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MESSAGE_DPOI_H
