// Generated by gencpp from file manipulation/harvest.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_HARVEST_H
#define MANIPULATION_MESSAGE_HARVEST_H

#include <ros/service_traits.h>


#include <manipulation/harvestRequest.h>
#include <manipulation/harvestResponse.h>


namespace manipulation
{

struct harvest
{

typedef harvestRequest Request;
typedef harvestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct harvest
} // namespace manipulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation::harvest > {
  static const char* value()
  {
    return "49ea530aae91150cd4645ab17a741cf0";
  }

  static const char* value(const ::manipulation::harvest&) { return value(); }
};

template<>
struct DataType< ::manipulation::harvest > {
  static const char* value()
  {
    return "manipulation/harvest";
  }

  static const char* value(const ::manipulation::harvest&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation::harvestRequest> should match
// service_traits::MD5Sum< ::manipulation::harvest >
template<>
struct MD5Sum< ::manipulation::harvestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation::harvest >::value();
  }
  static const char* value(const ::manipulation::harvestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation::harvestRequest> should match
// service_traits::DataType< ::manipulation::harvest >
template<>
struct DataType< ::manipulation::harvestRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation::harvest >::value();
  }
  static const char* value(const ::manipulation::harvestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation::harvestResponse> should match
// service_traits::MD5Sum< ::manipulation::harvest >
template<>
struct MD5Sum< ::manipulation::harvestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation::harvest >::value();
  }
  static const char* value(const ::manipulation::harvestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation::harvestResponse> should match
// service_traits::DataType< ::manipulation::harvest >
template<>
struct DataType< ::manipulation::harvestResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation::harvest >::value();
  }
  static const char* value(const ::manipulation::harvestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MESSAGE_HARVEST_H
