// Generated by gencpp from file manipulation/multi_frame.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_MULTI_FRAME_H
#define MANIPULATION_MESSAGE_MULTI_FRAME_H

#include <ros/service_traits.h>


#include <manipulation/multi_frameRequest.h>
#include <manipulation/multi_frameResponse.h>


namespace manipulation
{

struct multi_frame
{

typedef multi_frameRequest Request;
typedef multi_frameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multi_frame
} // namespace manipulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation::multi_frame > {
  static const char* value()
  {
    return "49ea530aae91150cd4645ab17a741cf0";
  }

  static const char* value(const ::manipulation::multi_frame&) { return value(); }
};

template<>
struct DataType< ::manipulation::multi_frame > {
  static const char* value()
  {
    return "manipulation/multi_frame";
  }

  static const char* value(const ::manipulation::multi_frame&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation::multi_frameRequest> should match
// service_traits::MD5Sum< ::manipulation::multi_frame >
template<>
struct MD5Sum< ::manipulation::multi_frameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation::multi_frame >::value();
  }
  static const char* value(const ::manipulation::multi_frameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation::multi_frameRequest> should match
// service_traits::DataType< ::manipulation::multi_frame >
template<>
struct DataType< ::manipulation::multi_frameRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation::multi_frame >::value();
  }
  static const char* value(const ::manipulation::multi_frameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation::multi_frameResponse> should match
// service_traits::MD5Sum< ::manipulation::multi_frame >
template<>
struct MD5Sum< ::manipulation::multi_frameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation::multi_frame >::value();
  }
  static const char* value(const ::manipulation::multi_frameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation::multi_frameResponse> should match
// service_traits::DataType< ::manipulation::multi_frame >
template<>
struct DataType< ::manipulation::multi_frameResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation::multi_frame >::value();
  }
  static const char* value(const ::manipulation::multi_frameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MESSAGE_MULTI_FRAME_H
