// Generated by gencpp from file manipulation/visual_servoResponse.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_VISUAL_SERVORESPONSE_H
#define MANIPULATION_MESSAGE_VISUAL_SERVORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulation
{
template <class ContainerAllocator>
struct visual_servoResponse_
{
  typedef visual_servoResponse_<ContainerAllocator> Type;

  visual_servoResponse_()
    : reply(0)  {
    }
  visual_servoResponse_(const ContainerAllocator& _alloc)
    : reply(0)  {
  (void)_alloc;
    }



   typedef int16_t _reply_type;
  _reply_type reply;





  typedef boost::shared_ptr< ::manipulation::visual_servoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation::visual_servoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct visual_servoResponse_

typedef ::manipulation::visual_servoResponse_<std::allocator<void> > visual_servoResponse;

typedef boost::shared_ptr< ::manipulation::visual_servoResponse > visual_servoResponsePtr;
typedef boost::shared_ptr< ::manipulation::visual_servoResponse const> visual_servoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation::visual_servoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation::visual_servoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulation::visual_servoResponse_<ContainerAllocator1> & lhs, const ::manipulation::visual_servoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reply == rhs.reply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulation::visual_servoResponse_<ContainerAllocator1> & lhs, const ::manipulation::visual_servoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulation::visual_servoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation::visual_servoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::visual_servoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::visual_servoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::visual_servoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::visual_servoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation::visual_servoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8649bbb6dd4aac4f3d4e2a496294c98f";
  }

  static const char* value(const ::manipulation::visual_servoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8649bbb6dd4aac4fULL;
  static const uint64_t static_value2 = 0x3d4e2a496294c98fULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation::visual_servoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation/visual_servoResponse";
  }

  static const char* value(const ::manipulation::visual_servoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation::visual_servoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 reply\n"
;
  }

  static const char* value(const ::manipulation::visual_servoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation::visual_servoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct visual_servoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation::visual_servoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation::visual_servoResponse_<ContainerAllocator>& v)
  {
    s << indent << "reply: ";
    Printer<int16_t>::stream(s, indent + "  ", v.reply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MESSAGE_VISUAL_SERVORESPONSE_H
